In [1]:
import pandas as pd
from sklearn.datasets import load_iris


C:\Users\A-Rajesh.Gaikwad\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\A-Rajesh.Gaikwad\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
data = load_iris()

In [4]:
df = pd.DataFrame(data['data'])

In [5]:
df.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [6]:
from sklearn.decomposition import PCA

C:\Users\A-Rajesh.Gaikwad\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\A-Rajesh.Gaikwad\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [42]:
pca = PCA(n_components=0.95)
X2D = pca.fit(df)

In [43]:
pca.explained_variance_ratio_

array([0.92461872, 0.05306648])

In [44]:
import numpy as np

In [45]:
cumsum = np.cumsum(pca.explained_variance_ratio_)
d = np.argmax(cumsum >= 0.95) + 1

In [46]:
cumsum

array([0.92461872, 0.97768521])

In [47]:
d

2

In [48]:
x_new = pd.DataFrame(X2D.transform(df))

In [49]:
x_new.head()

0         1
0 -2.684126  0.319397
1 -2.714142 -0.177001
2 -2.888991 -0.144949
3 -2.745343 -0.318299
4 -2.728717  0.326755

## Compressed datasets can be decompressed

In [50]:
X_recovered = pca.inverse_transform(x_new)

In [52]:
X_decompressed = pd.DataFrame(X_recovered)

In [53]:
X_decompressed.head()

0         1         2         3
0  5.083039  3.517414  1.403214  0.213532
1  4.746262  3.157500  1.463562  0.240246
2  4.704119  3.195682  1.308217  0.175180
3  4.642212  3.056967  1.461330  0.239732
4  5.071755  3.526555  1.363738  0.197000

## Randomized PCA

## Incremental PCA

## Alternate Approach using np.memmap

In [58]:
np.linspace(0.03, 0.05, 10)

array([0.03      , 0.03222222, 0.03444444, 0.03666667, 0.03888889,
       0.04111111, 0.04333333, 0.04555556, 0.04777778, 0.05      ])

array([10, 15])